# Generated by Django 5.1.6 on 2025-02-16 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_chatapp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChannel',
            new_name='UserBotChannel',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='UserBotMessage',
        ),
    ]
