# Generated by Django 5.1.6 on 2025-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_all_products', '0002_alter_subproductcategory_sub_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
