# Generated by Django 5.1.2 on 2025-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_all_products', '0004_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
