# Generated by Django 5.1.6 on 2025-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubProductCategory',
        ),
    ]
